eh - DriverAvailabilityForm + tests + stories
ucsb-cs156-w24/proj-gauchoride-w24-7pm-2 pull request #43
Opened 2024-03-01 03:52 UTC by elaineeeho

Implemented the DriverAvailabilityForm, tests for the form, and stories implementation

Closes #12

2024-03-01 06:30 UTC, andy-gale submitted a review, later dismissed
Ran locally. Looks good to me.

2024-03-01 07:40 UTC, ashton-wong submitted a review, later dismissed
LGTM

2024-03-04 07:05 UTC, andrewpengucsb requested changes

2024-03-04 07:05 UTC, andrewpengucsb commented on frontend/src/main/components/Driver/DriverAvailabilityForm.js
> +                    <Form.Label htmlFor="id">id</Form.Label>
Form labels should be capitalized, lowercase is a bit unprofessional and is inconsistent with other forms in the application

2024-03-06 02:17 UTC, michaelw1985 approved these changes
LGTM

2024-03-06 19:21 UTC, andrewpengucsb approved these changes

2024-03-06 19:35 UTC, merged